import { createHash, randomUUID } from 'node:crypto';
import { appendFile, mkdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { reverseKeys } from './dataset.ts';
import { buildState, decide, QUESTIONS } from './judgments.ts';
import { buildRequest, config, invoke } from './providers.ts';
import { fixtureFetch } from './runner.ts';
import { BENCHMARK_MANIFEST_HASH, EXECUTION_FREEZE, verifyExecutionFreeze } from './frozen-benchmark.ts';
import type { Answer, Answers, Provider, RunRecord, Scenario } from './types.ts';

const benchmarkDir='benchmark/v1';
const defaultBaseRun='results/benchmark-v1/2026-09-23T02-04-26-591Z-frozen-benchmark-v1-live';
const defaultRepeatRun='results/benchmark-v1/2026-09-23T02-35-43-756Z-frozen-repeatability-v1-live-c192f906';
const shaJson=(x:unknown)=>createHash('sha256').update(JSON.stringify(x)).digest('hex');
const shaText=(x:string)=>createHash('sha256').update(x).digest('hex');
const readJson=async(path:string)=>JSON.parse(await readFile(path,'utf8'));
const classify=(a:Answer)=>a.type==='noul'?a.noul!>=0.5:a.type==='choice'?a.choice:Number(Object.entries(a.probabilities!).sort((x,y)=>y[1]-x[1])[0][0]);
const matches=(a:Answers,expected:Record<string,boolean|string|number>)=>Object.fromEntries(Object.entries(expected).map(([id,g])=>[id,classify(a[id])===g]));
const percentile=(x:number[],p:number)=>x.length?[...x].sort((a,b)=>a-b)[Math.ceil(x.length*p)-1]:null;
const ratio=(n:number,d:number)=>d?n/d:null;
const cloneExceptType=(s:Scenario)=>{const c=structuredClone(s.observable);delete (c.profile as any).type;return c;};
const variantState=(s:Scenario)=>s.variant==='information-order'?reverseKeys(buildState(s)):buildState(s);

function performanceMetrics(rows:RunRecord[]){
 const times=rows.filter(r=>r.status==='ok').map(r=>r.latencyMs);
 const usage=(key:'inputTokens'|'cachedInputTokens'|'cacheWriteTokens'|'outputTokens'|'reasoningTokens')=>rows.reduce((n,r)=>n+(r.usage?.[key]??0),0);
 return{success:rows.filter(r=>r.status==='ok').length,failure:rows.filter(r=>r.status==='error').length,errors:rows.filter(r=>r.status==='error').length,retries:rows.reduce((n,r)=>n+Math.max(0,r.attempts.length-1),0),latencyMeanMs:times.length?times.reduce((a,b)=>a+b,0)/times.length:null,latencyP50Ms:percentile(times,.5),latencyP95Ms:percentile(times,.95),totalInferenceLatencyMs:rows.reduce((n,r)=>n+r.latencyMs,0),inputTokens:usage('inputTokens'),cachedInputTokens:usage('cachedInputTokens'),cacheWriteTokens:usage('cacheWriteTokens'),outputTokens:usage('outputTokens'),reasoningTokens:usage('reasoningTokens'),knownEstimatedCostUsd:rows.reduce((n,r)=>n+(r.estimatedCostUsd??0),0),costComplete:rows.every(r=>r.costComplete)};
}

function detail(variant:Scenario,record:RunRecord,base:RunRecord,gold:any){
 const atomic=Object.fromEntries(Object.keys(QUESTIONS).map(id=>{const b=base.answers?.[id]??null;const v=record.answers?.[id]??null;return[id,{gold:gold.expected[id],baseOutput:b,variantOutput:v,baseHardLabel:b?classify(b):null,variantHardLabel:v?classify(v):null,hardLabelAgreement:b&&v?classify(b)===classify(v):null,variantGoldMatch:record.atomicMatches?.[id]??null,probabilityDelta:b&&v?(v.type==='noul'?{deltaPYes:v.noul!-b.noul!,absoluteDeltaPYes:Math.abs(v.noul!-b.noul!)}:{perKey:Object.fromEntries(Object.keys(v.probabilities!).map(k=>[k,v.probabilities![k]-b.probabilities![k]])),distributionL1:Object.keys(v.probabilities!).reduce((n,k)=>n+Math.abs(v.probabilities![k]-b.probabilities![k]),0)}):null}]}));
 const changedAtomic=Object.entries(atomic).filter(([,v]:any)=>v.hardLabelAgreement===false).map(([id])=>id);
 return{baseCaseId:variant.baseId,variantId:variant.id,transformationType:variant.variant,provider:record.provider,goldAction:gold.correctAction,baseAction:base.decision?.action??null,variantAction:record.decision?.action??null,baseCorrect:base.correct,variantCorrect:record.correct,baseVariantActionAgreement:base.decision&&record.decision?base.decision.action===record.decision.action:null,baseDecisionRule:base.decision?.rule??null,variantDecisionRule:record.decision?.rule??null,atomic,changedAtomicDecisions:changedAtomic,atomicAgreementCount:Object.values(atomic).filter((v:any)=>v.hardLabelAgreement===true).length,atomicChangedWithoutActionChange:base.decision&&record.decision?changedAtomic.length>0&&base.decision.action===record.decision.action:null,latencyMs:record.latencyMs,firstAttemptLatencyMs:record.firstAttemptLatencyMs,usage:record.usage,estimatedCostUsd:record.estimatedCostUsd,error:record.error,retries:Math.max(0,record.attempts.length-1),httpStatuses:record.attempts.map(a=>a.status),requestIds:record.attempts.map(a=>a.requestId)};
}

function aggregate(rows:any[],denominator:number){
 const ok=rows.filter(x=>x.variantAction!==null);const changedAtomic=rows.reduce((n,x)=>n+x.changedAtomicDecisions.length,0);
 return{variants:denominator,successful:ok.length,failed:denominator-ok.length,actionAgreement:{count:rows.filter(x=>x.baseVariantActionAgreement===true).length,total:denominator,rate:ratio(rows.filter(x=>x.baseVariantActionAgreement===true).length,denominator)},groundTruthAccuracy:{correct:rows.filter(x=>x.variantCorrect===true).length,total:denominator,accuracy:ratio(rows.filter(x=>x.variantCorrect===true).length,denominator)},atomicAgreement:{count:rows.reduce((n,x)=>n+x.atomicAgreementCount,0),total:denominator*8,rate:ratio(rows.reduce((n,x)=>n+x.atomicAgreementCount,0),denominator*8)},changedAtomicDecisions:changedAtomic,incorrectVariants:rows.filter(x=>x.variantCorrect!==true).map(x=>x.variantId),atomicChangedButActionSame:rows.filter(x=>x.atomicChangedWithoutActionChange===true).map(x=>x.variantId)};
}

function markdownTable(headers:string[],rows:(string|number)[][]){return['| '+headers.join(' | ')+' |','|'+headers.map(()=>'---').join('|')+'|',...rows.map(r=>'| '+r.join(' | ')+' |')].join('\n');}
function reportMarkdown(title:string,body:string[]){return['# '+title,'',...body].join('\n')+'\n';}

export async function runFrozenConsistency(options:{offline?:boolean;outputRoot?:string;baseRunDirectory?:string;repeatRunDirectory?:string;onRecord?:(r:RunRecord)=>void}={}){
 const gate=await verifyExecutionFreeze();if(!gate.pass)throw new Error(`Frozen benchmark integrity failed: ${JSON.stringify(gate.mismatches)}`);
 if(gate.freeze.components.consistencyVariants!==shaText(await readFile(join(benchmarkDir,'consistency-variants.json'),'utf8'))||gate.freeze.components.consistencyDesign!==shaJson(gate.manifest.consistency))throw new Error('Frozen consistency hash mismatch');
 const [allCases,variants,gold,baseManifest,baseText,repeatManifest,repeatSummary,repeatCaseReport]=await Promise.all([readJson(join(benchmarkDir,'cases.json')),readJson(join(benchmarkDir,'consistency-variants.json')),readJson(join(benchmarkDir,'gold-proposed.json')),readJson(join(options.baseRunDirectory??defaultBaseRun,'manifest.json')),readFile(join(options.baseRunDirectory??defaultBaseRun,'records.jsonl'),'utf8'),readJson(join(options.repeatRunDirectory??defaultRepeatRun,'manifest.json')),readJson(join(options.repeatRunDirectory??defaultRepeatRun,'summary.json')),readJson(join(options.repeatRunDirectory??defaultRepeatRun,'case-report.json'))]);
 const sourceIds:string[]=gate.manifest.consistency.baseCaseIds;const types:string[]=gate.manifest.consistency.variantTypes;
 if(sourceIds.length!==12||variants.length!==48||types.join()!=='paraphrase,information-order,irrelevant-information,species-swap')throw new Error('Frozen consistency design is not 12 families × 4 types');
 if(baseManifest.mode!=='live'||baseManifest.suite!=='frozen-base-only'||!baseManifest.complete||baseManifest.executionFreezeHash!==EXECUTION_FREEZE||baseManifest.benchmarkManifestHash!==BENCHMARK_MANIFEST_HASH)throw new Error('Base Benchmark provenance mismatch');
 if(repeatManifest.mode!=='live'||repeatManifest.suite!=='frozen-repeatability-only'||!repeatManifest.complete||repeatManifest.executionFreezeHash!==EXECUTION_FREEZE||repeatSummary.requestRecords!==200)throw new Error('Repeatability reference provenance mismatch');
 const baseRecords:RunRecord[]=baseText.trim().split('\n').map(line=>JSON.parse(line));if(baseRecords.length!==240)throw new Error('Base Benchmark record count mismatch');
 const sources:Scenario[]=sourceIds.map(id=>{const c=allCases.find((s:Scenario)=>s.id===id);if(!c||!gold[id])throw new Error(`Unknown source case ${id}`);return c;});
 const speciesEvidenceChecks:any[]=[];
 for(const source of sources){
  const family=variants.filter((v:Scenario)=>v.baseId===source.id);if(family.length!==4||types.some(t=>family.filter((v:Scenario)=>v.variant===t).length!==1))throw new Error(`Invalid variant family ${source.id}`);
  const swapped=family.find((v:Scenario)=>v.variant==='species-swap')!;const evidencePreserved=shaJson(cloneExceptType(swapped))===shaJson(cloneExceptType(source));if(!evidencePreserved||swapped.observable.profile.type===source.observable.profile.type)throw new Error(`Species-swap evidence changed or type was not swapped: ${source.id}`);
  speciesEvidenceChecks.push({baseCaseId:source.id,variantId:swapped.id,baseSpecies:source.observable.profile.type,variantSpecies:swapped.observable.profile.type,decisionRelevantEvidencePreserved:true});
  for(const provider of ['jev','llm'] as Provider[]){const base=baseRecords.filter(r=>r.caseId===source.id&&r.provider===provider);if(base.length!==1||base[0].stateHash!==shaJson(buildState(source)))throw new Error(`Base state mismatch: ${source.id} ${provider}`);}
 }
 if(variants.some((v:Scenario)=>!sourceIds.includes(v.baseId)||!types.includes(v.variant)))throw new Error('Unexpected consistency variant');
 const configs=(['jev','llm'] as Provider[]).map(config);for(const c of configs){const frozen=gate.manifest.modelSettings[c.provider];if(c.model!==frozen.model||c.reasoningEffort!==(frozen.reasoningEffort??null))throw new Error(`Frozen model settings mismatch for ${c.provider}`);if(!options.offline&&!c.key)throw new Error(`Missing API key for ${c.provider}`);}
 const runId=`${new Date().toISOString().replace(/[:.]/g,'-')}-frozen-consistency-v1-${options.offline?'offline-fixture':'live'}-${randomUUID().slice(0,8)}`;const directory=join(options.outputRoot??'results/benchmark-v1',runId);await mkdir(directory,{recursive:true});const startedAt=new Date().toISOString();
 let manifest:any={schemaVersion:1,runId,benchmarkVersion:'v1',suite:'frozen-consistency-only',mode:options.offline?'offline-fixture':'live',excludedFromBaseAccuracy:true,executionFreezeHash:EXECUTION_FREEZE,benchmarkManifestHash:BENCHMARK_MANIFEST_HASH,consistencyDesignHash:gate.freeze.components.consistencyDesign,consistencyVariantsHash:gate.freeze.components.consistencyVariants,casesHash:gate.freeze.components.cases,goldHash:gate.freeze.components.gold,judgmentsSourceHash:gate.freeze.components.judgmentsSource,humanReviewStatus:gate.freeze.humanReviewStatus,modelSettings:gate.manifest.modelSettings,sourceCaseIds:sourceIds,variantIds:variants.map((v:Scenario)=>v.id),transformationTypes:types,baseRunDirectory:options.baseRunDirectory??defaultBaseRun,baseRecordsHash:shaText(baseText),repeatRunDirectory:options.repeatRunDirectory??defaultRepeatRun,repeatabilityReferenceHash:shaJson(repeatSummary),providers:configs.map(c=>({provider:c.provider,requestedModel:c.model,resolvedModel:null,reasoningEffort:c.reasoningEffort,pricingAssumptions:c.pricingAssumptions})),executionStartedAt:startedAt,executionEndedAt:null,execution:'48 variants only; existing Base responses are comparison values; sequential requests; provider order alternates within each family and is counterbalanced per transformation across families; no application cache; Ground Truth excluded from requests',apiErrorRetryPolicy:'Retry HTTP 429/500/502/503/504/529 once; honor Retry-After up to 30 seconds; do not retry ambiguous network failures; persist all attempts and failures.',probabilitySemantics:'Jev Noul P(Yes), Choice/Score distributions and Jev confidence are provider-native. Luna probabilities are generated self-estimates and are not the same confidence metric.',interpretation:'Observed base-to-variant consistency is not a causal transformation effect; same-input stochasticity is reported separately.',speciesEvidenceChecks,preRunIntegrity:{pass:true,componentMismatches:0},complete:false};
 await writeFile(join(directory,'manifest.json'),JSON.stringify(manifest,null,2));await writeFile(join(directory,'frozen-input-snapshot.json'),JSON.stringify({freeze:gate.freeze,benchmarkManifest:gate.manifest,sourceCases:sources,variants,gold:Object.fromEntries(sourceIds.map(id=>[id,gold[id]])),baseRecordsHash:shaText(baseText)},null,2));
 const records:RunRecord[]=[];let stop=false;const wallStart=performance.now();
 for(let i=0;i<variants.length&&!stop;i++){const v:Scenario=variants[i];const state=variantState(v);const ordered=(i+Math.floor(i/4))%2?[...configs].reverse():configs;for(const c of ordered){const request=buildRequest(c.provider,c.model,state,c.reasoningEffort);const started=new Date().toISOString();const response=await invoke(c,request,options.offline?fixtureFetch(c.provider):fetch);const g=gold[v.baseId];const decision=response.answers?decide(response.answers):null;const record:RunRecord={schemaVersion:1,runId,mode:options.offline?'offline-fixture':'live',caseId:v.id,baseId:v.baseId,variant:v.variant,provider:c.provider,modelRequested:c.model,reasoningEffort:c.reasoningEffort,stateHash:shaJson(state),request,groundTruth:g,decision,correct:decision?decision.action===g.correctAction:null,atomicMatches:response.answers?matches(response.answers,g.expected):null,status:response.answers?'ok':'error',startedAt:started,firstAttemptLatencyMs:response.attempts[0]?.latencyMs??0,...response};records.push(record);await appendFile(join(directory,'records.jsonl'),JSON.stringify(record)+'\n');options.onRecord?.(record);if(response.attempts.some(a=>[401,402,403].includes(a.status!)))stop=true;}}
 const details=variants.flatMap((v:Scenario)=>(['jev','llm'] as Provider[]).map(provider=>{const r=records.find(x=>x.caseId===v.id&&x.provider===provider);const b=baseRecords.find(x=>x.caseId===v.baseId&&x.provider===provider)!;return r?detail(v,r,b,gold[v.baseId]):null}).filter(Boolean));
 const families=sourceIds.map(id=>({baseCaseId:id,goldAction:gold[id].correctAction,providers:(['jev','llm'] as Provider[]).map(provider=>{const base=baseRecords.find(x=>x.caseId===id&&x.provider===provider)!;const family=details.filter((x:any)=>x.baseCaseId===id&&x.provider===provider);const repeat=repeatCaseReport.find((x:any)=>x.caseId===id)?.providers.find((p:any)=>p.provider===provider);return{provider,baseAction:base.decision?.action??null,baseCorrect:base.correct,baseDecisionRule:base.decision?.rule??null,variants:family,allFamilyCorrect:base.correct===true&&family.length===4&&family.every((x:any)=>x.variantCorrect===true),repeatabilityReference:repeat?{actionCounts:repeat.actionCounts,all5Agreement:repeat.all5Agreement,modalAgreementRate:repeat.modalAgreementRate}:null};})}));
 const providerSummaries=(['jev','llm'] as Provider[]).map(provider=>{const rows=details.filter((x:any)=>x.provider===provider);const raw=records.filter(r=>r.provider===provider);const transitions={correctBaseToIncorrectVariant:rows.filter((x:any)=>x.baseCorrect===true&&x.variantCorrect!==true).length,incorrectBaseToCorrectVariant:rows.filter((x:any)=>x.baseCorrect===false&&x.variantCorrect===true).length,correctBaseToCorrectVariantSameAction:rows.filter((x:any)=>x.baseCorrect===true&&x.variantCorrect===true&&x.baseVariantActionAgreement===true).length,baseVariantBothIncorrect:rows.filter((x:any)=>x.baseCorrect===false&&x.variantCorrect===false).length};const atomic=Object.fromEntries(Object.keys(QUESTIONS).map(id=>{const changed=rows.filter((x:any)=>x.atomic[id].hardLabelAgreement===false);const agreement=rows.filter((x:any)=>x.atomic[id].hardLabelAgreement===true).length;const correct=rows.filter((x:any)=>x.atomic[id].variantGoldMatch===true).length;return[id,{baseVariantHardLabelAgreement:{count:agreement,total:48,rate:agreement/48},variantGroundTruthAccuracy:{correct,total:48,accuracy:correct/48},changedAtomicDecisions:changed.length,changedVariantIds:changed.map((x:any)=>x.variantId)}]}));return{provider,...aggregate(rows,48),transitions,allFamilyCorrect:{count:families.filter(f=>f.providers.find((p:any)=>p.provider===provider)?.allFamilyCorrect).length,total:12},atomic,performance:performanceMetrics(raw)};});
 const transformations=types.flatMap(type=>(['jev','llm'] as Provider[]).map(provider=>({transformationType:type,provider,...aggregate(details.filter((x:any)=>x.transformationType===type&&x.provider===provider),12)})));
 const species=speciesEvidenceChecks.map(check=>({...check,providers:(['jev','llm'] as Provider[]).map(provider=>{const d=details.find((x:any)=>x.variantId===check.variantId&&x.provider===provider);return{provider,baseAction:d?.baseAction??null,variantAction:d?.variantAction??null,actionChanged:d?.baseVariantActionAgreement===null?null:!d.baseVariantActionAgreement,changedAtomicJudgments:d?.changedAtomicDecisions??[],baseCorrect:d?.baseCorrect??null,variantCorrect:d?.variantCorrect??null,groundTruthCorrectnessChanged:d?.baseCorrect!==null&&d?.variantCorrect!==null?d.baseCorrect!==d.variantCorrect:null};})}));
 const repeatabilityReference={sourceRunDirectory:options.repeatRunDirectory??defaultRepeatRun,jev:{all5FinalActionAgreement:'19/20; remaining one case has HTTP 520 missing response',successfulFinalActionErrors:0,successfulResponses:99},luna:{all5FinalActionAgreement:'13/20',meanModalAgreement:0.93,finalActionAccuracy:'93/100'},overlappingSourceCaseIds:sourceIds.filter(id=>repeatCaseReport.some((x:any)=>x.caseId===id)),note:'Same-input stochasticity is a separate reference, not combined into a consistency score.'};
 const summary={benchmarkVersion:'v1',suite:'frozen-consistency-only',executionFreezeHash:EXECUTION_FREEZE,consistencyDesignHash:gate.freeze.components.consistencyDesign,consistencyVariantsHash:gate.freeze.components.consistencyVariants,sourceFamilies:12,variants:48,expectedRequests:96,requestRecords:records.length,complete:records.length===96,providers:providerSummaries,transformations,repeatabilityReference,wallElapsedMs:performance.now()-wallStart};
 await writeFile(join(directory,'summary.json'),JSON.stringify(summary,null,2));await writeFile(join(directory,'case-level.json'),JSON.stringify(details,null,2));await writeFile(join(directory,'family-report.json'),JSON.stringify(families,null,2));await writeFile(join(directory,'species-swap-report.json'),JSON.stringify(species,null,2));await writeFile(join(directory,'atomic-consistency-report.json'),JSON.stringify({providers:providerSummaries.map(p=>({provider:p.provider,atomic:p.atomic,atomicChangedButActionSame:p.atomicChangedButActionSame})),caseLevel:details.map((x:any)=>({variantId:x.variantId,provider:x.provider,changedAtomicDecisions:x.changedAtomicDecisions,atomicChangedWithoutActionChange:x.atomicChangedWithoutActionChange,atomic:x.atomic}))},null,2));await writeFile(join(directory,'post-run-observations.json'),JSON.stringify({benchmarkVersion:'v1',freezeHash:EXECUTION_FREEZE,datasetMutations:0,observations:[]},null,2));
 const fm=['Observed Base→Variant differences include same-input stochasticity. They are not causal estimates of the transformations.','',markdownTable(['Base','Gold','Jev Base','Jev variants','Jev all correct','Luna Base','Luna variants','Luna all correct'],families.map(f=>{const j=f.providers[0],l=f.providers[1];return[f.baseCaseId,f.goldAction,j.baseAction,j.variants.map((v:any)=>v.variantAction??'ERROR').join(', '),String(j.allFamilyCorrect),l.baseAction,l.variants.map((v:any)=>v.variantAction??'ERROR').join(', '),String(l.allFamilyCorrect)];})),''];await writeFile(join(directory,'family-report.md'),reportMarkdown('Consistency family-level report',fm));
 const sm=['Frozen design check: for every species-swap, profile.type changes while the rest of the observable evidence is byte-equivalent after removing profile.type. Species, origin, and politeness are not decision evidence under the frozen policy.','',markdownTable(['Base','Species swap','Provider','Base→Variant action','Changed atomic judgments','Correctness changed'],species.flatMap(s=>s.providers.map((p:any)=>[s.baseCaseId,`${s.baseSpecies}→${s.variantSpecies}`,p.provider,`${p.baseAction}→${p.variantAction??'ERROR'}`,p.changedAtomicJudgments.join(', ')||'none',String(p.groundTruthCorrectnessChanged)]))),'','These are observed attribute sensitivities. No internal cause or intent is inferred.'];await writeFile(join(directory,'species-swap-report.md'),reportMarkdown('Species-swap report',sm));
 const am=[markdownTable(['Judgment','Jev agreement','Jev Gold accuracy','Jev changes','Luna agreement','Luna Gold accuracy','Luna changes'],Object.keys(QUESTIONS).map(id=>{const j=providerSummaries[0].atomic[id],l=providerSummaries[1].atomic[id];return[id,`${j.baseVariantHardLabelAgreement.count}/48`,`${j.variantGroundTruthAccuracy.correct}/48`,j.changedAtomicDecisions,`${l.baseVariantHardLabelAgreement.count}/48`,`${l.variantGroundTruthAccuracy.correct}/48`,l.changedAtomicDecisions]})),'',`Atomic changed without final-action change: Jev ${providerSummaries[0].atomicChangedButActionSame.length}; Luna ${providerSummaries[1].atomicChangedButActionSame.length}.`,'','Full native probabilities, distributions, and per-judgment deltas are in atomic-consistency-report.json.'];await writeFile(join(directory,'atomic-consistency-report.md'),reportMarkdown('Atomic consistency report',am));
 const overall=['Observed consistency; Base responses are one existing draw and variants are one new draw. Same-input repeatability is kept as a separate reference.','',markdownTable(['Provider','Action agreement','Variant Gold accuracy','Atomic agreement','All-family-correct','Errors','Retries'],providerSummaries.map(p=>[p.provider,`${p.actionAgreement.count}/48`,`${p.groundTruthAccuracy.correct}/48`,`${p.atomicAgreement.count}/384`,`${p.allFamilyCorrect.count}/12`,p.performance.errors,p.performance.retries])),'','Repeatability reference: Jev 19/20 all-5 (one HTTP 520 missing), 0 final-action errors among 99 successful responses; Luna 13/20 all-5, mean modal agreement 93%, accuracy 93/100. These values are not combined with consistency.',''];await writeFile(join(directory,'summary.md'),reportMarkdown('Frozen Held-out Benchmark v1 — Consistency',overall));
 const tm=[markdownTable(['Transformation','Provider','Action agreement','Gold accuracy','Atomic agreement','Atomic changes','Incorrect variants'],transformations.map(t=>[t.transformationType,t.provider,`${t.actionAgreement.count}/12`,`${t.groundTruthAccuracy.correct}/12`,`${t.atomicAgreement.count}/96`,t.changedAtomicDecisions,t.incorrectVariants.join(', ')||'none'])),'','Differences are observed, not attributed causally to the transformation.'];await writeFile(join(directory,'transformation-summary.md'),reportMarkdown('Consistency by transformation',tm));
 manifest={...manifest,providers:configs.map(c=>({...manifest.providers.find((p:any)=>p.provider===c.provider),resolvedModel:(()=>{const x=[...new Set(records.filter(r=>r.provider===c.provider&&r.modelResolved).map(r=>r.modelResolved))];return x.length===1?x[0]:null;})()})),executionEndedAt:new Date().toISOString(),wallElapsedMs:summary.wallElapsedMs,complete:summary.complete};await writeFile(join(directory,'manifest.json'),JSON.stringify(manifest,null,2));
 return{directory,summary,records};
}
