import { createHash, randomUUID } from 'node:crypto';
import { appendFile, mkdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { buildState, decide, QUESTIONS } from './judgments.ts';
import { buildRequest, config, invoke } from './providers.ts';
import { fixtureFetch } from './runner.ts';
import { BENCHMARK_MANIFEST_HASH, EXECUTION_FREEZE, verifyExecutionFreeze } from './frozen-benchmark.ts';
import type { Answer, Answers, Provider, RunRecord, Scenario } from './types.ts';

const dir='benchmark/v1';
const baseRun='results/benchmark-v1/2026-09-23T02-04-26-591Z-frozen-benchmark-v1-live';
const consistencyRun='results/benchmark-v1/2026-09-23T03-14-34-775Z-frozen-consistency-v1-live-dfc8769b';
const sha=(s:string)=>createHash('sha256').update(s).digest('hex');
const shaJson=(x:unknown)=>sha(JSON.stringify(x));
const readJson=async(path:string)=>JSON.parse(await readFile(path,'utf8'));
const classify=(a:Answer)=>a.type==='noul'?a.noul!>=0.5:a.type==='choice'?a.choice:Number(Object.entries(a.probabilities!).sort((x,y)=>y[1]-x[1])[0][0]);
const matches=(a:Answers,g:Record<string,boolean|string|number>)=>Object.fromEntries(Object.entries(g).map(([id,v])=>[id,classify(a[id])===v]));
const percentile=(a:number[],p:number)=>a.length?[...a].sort((x,y)=>x-y)[Math.ceil(a.length*p)-1]:null;
const categories=['decisive-evidence-addition','decisive-evidence-deletion','evidence-polarity-reversal'];

function performanceMetrics(rows:RunRecord[]){
 const times=rows.filter(r=>r.status==='ok').map(r=>r.latencyMs);
 const usage=(key:'inputTokens'|'cachedInputTokens'|'cacheWriteTokens'|'outputTokens'|'reasoningTokens')=>rows.reduce((n,r)=>n+(r.usage?.[key]??0),0);
 return{successful:rows.filter(r=>r.status==='ok').length,failed:rows.filter(r=>r.status==='error').length,errors:rows.filter(r=>r.status==='error').length,retries:rows.reduce((n,r)=>n+Math.max(0,r.attempts.length-1),0),latencyMeanMs:times.length?times.reduce((a,b)=>a+b,0)/times.length:null,latencyP50Ms:percentile(times,.5),latencyP95Ms:percentile(times,.95),totalInferenceLatencyMs:rows.reduce((n,r)=>n+r.latencyMs,0),inputTokens:usage('inputTokens'),cachedInputTokens:usage('cachedInputTokens'),cacheWriteTokens:usage('cacheWriteTokens'),outputTokens:usage('outputTokens'),reasoningTokens:usage('reasoningTokens'),knownEstimatedCostUsd:rows.reduce((n,r)=>n+(r.estimatedCostUsd??0),0),costComplete:rows.every(r=>r.costComplete)};
}

function detail(v:Scenario,r:RunRecord,b:RunRecord,baseGold:any,variantGold:any){
 const atomic=Object.fromEntries(Object.keys(QUESTIONS).map(id=>{const baseOutput=b.answers?.[id]??null,variantOutput=r.answers?.[id]??null,baseLabel=baseOutput?classify(baseOutput):null,variantLabel=variantOutput?classify(variantOutput):null,baseExpected=baseGold.expected[id],variantExpected=variantGold.expected[id],expectedChange=baseExpected!==variantExpected,observedChange=baseLabel!==null&&variantLabel!==null?baseLabel!==variantLabel:null;return[id,{baseGold:baseExpected,variantGold:variantExpected,baseOutput,variantOutput,baseHardLabel:baseLabel,variantHardLabel:variantLabel,expectedChange,observedChange,exactGoldTransition:expectedChange&&baseLabel===baseExpected&&variantLabel===variantExpected,correctVariantLabel:variantLabel===variantExpected,missedExpectedChange:expectedChange&&observedChange===false,wrongDirectionChange:expectedChange&&observedChange===true&&variantLabel!==variantExpected,recoveredFromWrongBase:expectedChange&&observedChange===true&&baseLabel!==baseExpected&&variantLabel===variantExpected,unexpectedChange:!expectedChange&&observedChange===true,probabilityDelta:baseOutput&&variantOutput?(variantOutput.type==='noul'?{pYes:variantOutput.noul!-baseOutput.noul!}:{perKey:Object.fromEntries(Object.keys(variantOutput.probabilities!).map(k=>[k,variantOutput.probabilities![k]-baseOutput.probabilities![k]])),distributionL1:Object.keys(variantOutput.probabilities!).reduce((n,k)=>n+Math.abs(variantOutput.probabilities![k]-baseOutput.probabilities![k]),0)}):null}]}));
 const baseAction=b.decision?.action??null,variantAction=r.decision?.action??null,requiredActionChange=baseGold.correctAction!==variantGold.correctAction,observedActionChange=baseAction&&variantAction?baseAction!==variantAction:null;
 return{sourceBaseCaseId:v.baseId,variantId:v.id,transformationType:v.variant,provider:r.provider,baseGoldAction:baseGold.correctAction,variantGoldAction:variantGold.correctAction,baseModelAction:baseAction,variantModelAction:variantAction,requiredActionChange,observedActionChange,correctRequiredActionChange:observedActionChange===true&&variantAction===variantGold.correctAction,variantGoldCorrect:variantAction===variantGold.correctAction,baseCorrect:b.correct,exactGoldTransition:baseAction===baseGold.correctAction&&variantAction===variantGold.correctAction,baseDecisionRule:b.decision?.rule??null,variantDecisionRule:r.decision?.rule??null,atomic,expectedAtomicChanges:Object.keys(atomic).filter(id=>(atomic[id] as any).expectedChange),observedAtomicChanges:Object.keys(atomic).filter(id=>(atomic[id] as any).observedChange===true),latencyMs:r.latencyMs,firstAttemptLatencyMs:r.firstAttemptLatencyMs,usage:r.usage,estimatedCostUsd:r.estimatedCostUsd,status:r.status,error:r.error,retries:Math.max(0,r.attempts.length-1),httpStatuses:r.attempts.map(a=>a.status),requestIds:r.attempts.map(a=>a.requestId)};
}

function aggregate(rows:any[],expectedCount:number){
 const allAtomic=rows.flatMap(d=>Object.entries(d.atomic).map(([id,a])=>({variantId:d.variantId,id,...a as any})));
 const changed=allAtomic.filter(a=>a.expectedChange),unchanged=allAtomic.filter(a=>!a.expectedChange);
 return{variants:expectedCount,variantGoldAccuracy:{correct:rows.filter(d=>d.variantGoldCorrect).length,total:expectedCount},requiredActionChangeDetected:{count:rows.filter(d=>d.observedActionChange===true).length,total:expectedCount},correctRequiredActionChanges:{count:rows.filter(d=>d.correctRequiredActionChange).length,total:expectedCount},exactGoldTransitions:{count:rows.filter(d=>d.exactGoldTransition).length,total:expectedCount},transitions:{correctBaseToCorrectVariant:rows.filter(d=>d.baseCorrect===true&&d.variantGoldCorrect).length,incorrectBaseToCorrectVariant:rows.filter(d=>d.baseCorrect===false&&d.variantGoldCorrect).length,correctBaseToIncorrectVariant:rows.filter(d=>d.baseCorrect===true&&!d.variantGoldCorrect).length,incorrectBaseToIncorrectVariant:rows.filter(d=>d.baseCorrect===false&&!d.variantGoldCorrect).length},atomic:{expectedChanged:changed.length,correctlyChangedExactGoldTransition:changed.filter(a=>a.exactGoldTransition).length,missedExpectedChanges:changed.filter(a=>a.missedExpectedChange).length,wrongDirectionChanges:changed.filter(a=>a.wrongDirectionChange).length,recoveredFromWrongBase:changed.filter(a=>a.recoveredFromWrongBase).length,unexpectedChanges:unchanged.filter(a=>a.unexpectedChange).length,unexpectedChangeDetails:unchanged.filter(a=>a.unexpectedChange).map(a=>({variantId:a.variantId,judgment:a.id,baseGold:a.baseGold,variantGold:a.variantGold,baseHardLabel:a.baseHardLabel,variantHardLabel:a.variantHardLabel}))}};
}
const table=(headers:string[],rows:(string|number)[][])=>['| '+headers.join(' | ')+' |','|'+headers.map(()=>'---').join('|')+'|',...rows.map(r=>'| '+r.join(' | ')+' |')].join('\n');

export async function runFrozenSensitivity(options:{offline?:boolean;outputRoot?:string;onRecord?:(r:RunRecord)=>void}={}){
 const gate=await verifyExecutionFreeze();if(!gate.pass)throw new Error(`Frozen benchmark integrity failed: ${JSON.stringify(gate.mismatches)}`);
 const [variantsText,goldText,cases,baseGold,baseManifest,baseText,consistencyManifest,consistencySummary]=await Promise.all([readFile(join(dir,'sensitivity-variants.json'),'utf8'),readFile(join(dir,'sensitivity-gold-proposed.json'),'utf8'),readJson(join(dir,'cases.json')),readJson(join(dir,'gold-proposed.json')),readJson(join(baseRun,'manifest.json')),readFile(join(baseRun,'records.jsonl'),'utf8'),readJson(join(consistencyRun,'manifest.json')),readJson(join(consistencyRun,'summary.json'))]);
 if(sha(variantsText)!==gate.freeze.components.sensitivityVariants||sha(goldText)!==gate.freeze.components.sensitivityGold)throw new Error('Frozen sensitivity variants or Gold hash mismatch');
 const variants:Scenario[]=JSON.parse(variantsText),sensitivityGold=JSON.parse(goldText);
 if(variants.length!==9||Object.keys(sensitivityGold).length!==9||variants.filter(v=>v.variant===categories[0]).length!==2||variants.filter(v=>v.variant===categories[1]).length!==4||variants.filter(v=>v.variant===categories[2]).length!==3)throw new Error('Frozen sensitivity design is not 2 add, 4 delete, 3 polarity flip');
 if(baseManifest.mode!=='live'||baseManifest.suite!=='frozen-base-only'||!baseManifest.complete||baseManifest.executionFreezeHash!==EXECUTION_FREEZE||baseManifest.benchmarkManifestHash!==BENCHMARK_MANIFEST_HASH)throw new Error('Base Benchmark provenance mismatch');
 if(consistencyManifest.mode!=='live'||consistencyManifest.suite!=='frozen-consistency-only'||!consistencyManifest.complete||consistencyManifest.executionFreezeHash!==EXECUTION_FREEZE||consistencySummary.requestRecords!==96)throw new Error('Consistency reference provenance mismatch');
 const baseRecords:RunRecord[]=baseText.trim().split('\n').map(line=>JSON.parse(line));if(baseRecords.length!==240)throw new Error('Base Benchmark record count mismatch');
 for(const v of variants){const source:Scenario=cases.find((c:Scenario)=>c.id===v.baseId);if(!source||!baseGold[v.baseId]||!sensitivityGold[v.id]||baseGold[v.baseId].correctAction===sensitivityGold[v.id].correctAction||!sensitivityGold[v.id].scoringEligible)throw new Error(`Invalid frozen sensitivity variant ${v.id}`);for(const provider of ['jev','llm'] as Provider[]){const b=baseRecords.filter(r=>r.caseId===v.baseId&&r.provider===provider);if(b.length!==1||b[0].stateHash!==shaJson(buildState(source)))throw new Error(`Base state mismatch ${v.baseId} ${provider}`);}}
 const configs=(['jev','llm'] as Provider[]).map(config);for(const c of configs){const frozen=gate.manifest.modelSettings[c.provider];if(c.model!==frozen.model||c.reasoningEffort!==(frozen.reasoningEffort??null))throw new Error(`Frozen model settings mismatch for ${c.provider}`);if(!options.offline&&!c.key)throw new Error(`Missing API key for ${c.provider}`);}
 const runId=`${new Date().toISOString().replace(/[:.]/g,'-')}-frozen-sensitivity-v1-${options.offline?'offline-fixture':'live'}-${randomUUID().slice(0,8)}`,directory=join(options.outputRoot??'results/benchmark-v1',runId);await mkdir(directory,{recursive:true});const startedAt=new Date().toISOString();
 let manifest:any={schemaVersion:1,runId,benchmarkVersion:'v1',suite:'frozen-sensitivity-only',mode:options.offline?'offline-fixture':'live',excludedFromBaseAccuracy:true,executionFreezeHash:EXECUTION_FREEZE,benchmarkManifestHash:BENCHMARK_MANIFEST_HASH,sensitivityVariantsHash:gate.freeze.components.sensitivityVariants,sensitivityGoldHash:gate.freeze.components.sensitivityGold,casesHash:gate.freeze.components.cases,baseGoldHash:gate.freeze.components.gold,judgmentsSourceHash:gate.freeze.components.judgmentsSource,humanReviewStatus:gate.freeze.humanReviewStatus,modelSettings:gate.manifest.modelSettings,variantIds:variants.map(v=>v.id),sourceBaseCaseIds:variants.map(v=>v.baseId),baseRunDirectory:baseRun,baseRecordsHash:sha(baseText),consistencyRunDirectory:consistencyRun,consistencySummaryHash:shaJson(consistencySummary),providers:configs.map(c=>({provider:c.provider,requestedModel:c.model,resolvedModel:null,reasoningEffort:c.reasoningEffort,pricingAssumptions:c.pricingAssumptions})),executionStartedAt:startedAt,executionEndedAt:null,execution:'9 sensitivity variants only; existing Base responses are comparison values; sequential requests; provider order alternates; no application cache; Ground Truth excluded from requests',apiErrorRetryPolicy:'Retry HTTP 429/500/502/503/504/529 once; honor Retry-After up to 30 seconds; do not retry ambiguous network failures; persist all attempts and failures.',probabilitySemantics:'Jev Noul P(Yes), Choice/Score distributions and Jev confidence are provider-native. Luna probabilities are generated self-estimates and are not the same confidence metric.',preRunIntegrity:{pass:true,componentMismatches:0},complete:false};
 await writeFile(join(directory,'manifest.json'),JSON.stringify(manifest,null,2));await writeFile(join(directory,'frozen-input-snapshot.json'),JSON.stringify({freeze:gate.freeze,benchmarkManifest:gate.manifest,variants,sensitivityGold,baseGold:Object.fromEntries(variants.map(v=>[v.baseId,baseGold[v.baseId]])),baseRecordsHash:sha(baseText)},null,2));
 const records:RunRecord[]=[];let stop=false;const wallStart=performance.now();
 for(let i=0;i<variants.length&&!stop;i++){const v=variants[i];const state=buildState(v);const ordered=i%2?[...configs].reverse():configs;for(const c of ordered){const request=buildRequest(c.provider,c.model,state,c.reasoningEffort);const started=new Date().toISOString();const response=await invoke(c,request,options.offline?fixtureFetch(c.provider):fetch);const g=sensitivityGold[v.id];const decision=response.answers?decide(response.answers):null;const record:RunRecord={schemaVersion:1,runId,mode:options.offline?'offline-fixture':'live',caseId:v.id,baseId:v.baseId,variant:v.variant,provider:c.provider,modelRequested:c.model,reasoningEffort:c.reasoningEffort,stateHash:shaJson(state),request,groundTruth:g,decision,correct:decision?decision.action===g.correctAction:null,atomicMatches:response.answers?matches(response.answers,g.expected):null,status:response.answers?'ok':'error',startedAt:started,firstAttemptLatencyMs:response.attempts[0]?.latencyMs??0,...response};records.push(record);await appendFile(join(directory,'records.jsonl'),JSON.stringify(record)+'\n');options.onRecord?.(record);if(response.attempts.some(a=>[401,402,403].includes(a.status!)))stop=true;}}
 const details=variants.flatMap(v=>(['jev','llm'] as Provider[]).map(provider=>{const r=records.find(x=>x.caseId===v.id&&x.provider===provider),b=baseRecords.find(x=>x.caseId===v.baseId&&x.provider===provider)!;return r?detail(v,r,b,baseGold[v.baseId],sensitivityGold[v.id]):null}).filter(Boolean));
 const providerSummaries=(['jev','llm'] as Provider[]).map(provider=>({provider,...aggregate(details.filter((d:any)=>d.provider===provider),9),performance:performanceMetrics(records.filter(r=>r.provider===provider))}));
 const transformations=categories.flatMap(type=>(['jev','llm'] as Provider[]).map(provider=>({transformationType:type,provider,...aggregate(details.filter((d:any)=>d.transformationType===type&&d.provider===provider),variants.filter(v=>v.variant===type).length)})));
 const atomicByJudgment=(['jev','llm'] as Provider[]).map(provider=>({provider,judgments:Object.fromEntries(Object.keys(QUESTIONS).map(id=>{const rows=details.filter((d:any)=>d.provider===provider).map((d:any)=>({variantId:d.variantId,...d.atomic[id]}));const expected=rows.filter(x=>x.expectedChange),stable=rows.filter(x=>!x.expectedChange);return[id,{expectedChanged:expected.length,correctlyChangedExactGoldTransition:expected.filter(x=>x.exactGoldTransition).length,missedExpectedChanges:expected.filter(x=>x.missedExpectedChange).length,wrongDirectionChanges:expected.filter(x=>x.wrongDirectionChange).length,recoveredFromWrongBase:expected.filter(x=>x.recoveredFromWrongBase).length,unexpectedChanges:stable.filter(x=>x.unexpectedChange).length,caseLevel:rows}]}))}));
 const consistencyReference={sourceRunDirectory:consistencyRun,jev:{actionAgreement:'48/48',variantGoldAccuracy:'48/48',allFamilyCorrect:'12/12'},luna:{actionAgreement:'36/48',variantGoldAccuracy:'43/48',allFamilyCorrect:'7/12'},note:'Stability and responsiveness are separate measurements; no composite score is formed.'};
 const stabilityResponsiveness=(['jev','llm'] as Provider[]).map(provider=>{const consistency=consistencySummary.providers.find((p:any)=>p.provider===provider),sensitivity=providerSummaries.find(p=>p.provider===provider)!;return{provider,stabilityMeaningPreservingActionMaintained:{count:consistency.actionAgreement.count,total:48},responsivenessCorrectRequiredActionChange:{count:sensitivity.correctRequiredActionChanges.count,total:9},exactBaseGoldToVariantGoldTransition:{count:sensitivity.exactGoldTransitions.count,total:9}};});
 const summary={benchmarkVersion:'v1',suite:'frozen-sensitivity-only',executionFreezeHash:EXECUTION_FREEZE,sensitivityVariantsHash:gate.freeze.components.sensitivityVariants,sensitivityGoldHash:gate.freeze.components.sensitivityGold,variants:9,expectedRequests:18,requestRecords:records.length,complete:records.length===18,providers:providerSummaries,transformations,consistencyReference,stabilityResponsiveness,wallElapsedMs:performance.now()-wallStart};
 await writeFile(join(directory,'summary.json'),JSON.stringify(summary,null,2));await writeFile(join(directory,'case-level.json'),JSON.stringify(details,null,2));await writeFile(join(directory,'atomic-sensitivity-report.json'),JSON.stringify({providers:atomicByJudgment,definitions:{correctlyChangedExactGoldTransition:'Base model hard label equals Base Gold and variant hard label equals Variant Gold for a Gold-changing atomic judgment.',missedExpectedChange:'Base and variant model hard labels stay equal although Gold changed.',wrongDirectionChange:'Model hard label changes but the variant label does not equal Variant Gold.',recoveredFromWrongBase:'Model hard label changes to Variant Gold, but Base model label was already wrong.',unexpectedChange:'Model hard label changes although atomic Gold is unchanged.'}},null,2));await writeFile(join(directory,'post-run-observations.json'),JSON.stringify({benchmarkVersion:'v1',freezeHash:EXECUTION_FREEZE,datasetMutations:0,observations:[]},null,2));
 const overall=['All nine Variant Gold actions differ from their frozen Base Gold actions. A mere model action change is not counted as a correct response unless the variant action reaches Variant Gold.','',table(['Provider','Variant Gold','Any required change','Correct change to Gold','Exact Gold transition','Errors','Retries'],providerSummaries.map(p=>[p.provider,`${p.variantGoldAccuracy.correct}/9`,`${p.requiredActionChangeDetected.count}/9`,`${p.correctRequiredActionChanges.count}/9`,`${p.exactGoldTransitions.count}/9`,p.performance.errors,p.performance.retries])),'','Consistency reference is separate: Jev 48/48 action agreement, 48/48 Gold, 12/12 all-family-correct; Luna 36/48 action agreement, 43/48 Gold, 7/12 all-family-correct.',''];await writeFile(join(directory,'summary.md'),['# Frozen Held-out Benchmark v1 — Sensitivity','',...overall].join('\n'));
 const tm=[table(['Transformation','Provider','Variant Gold','Correct required action change','Expected atomic exact changes','Unexpected atomic changes'],transformations.map(t=>[t.transformationType,t.provider,`${t.variantGoldAccuracy.correct}/${t.variants}`,`${t.correctRequiredActionChanges.count}/${t.variants}`,`${t.atomic.correctlyChangedExactGoldTransition}/${t.atomic.expectedChanged}`,t.atomic.unexpectedChanges])),''];await writeFile(join(directory,'transformation-summary.md'),['# Sensitivity by transformation','',...tm].join('\n'));
 const cm=[table(['Variant','Type','Provider','Base Gold→Variant Gold','Base model→Variant model','Any change','Correct change','Exact Gold transition'],details.map((d:any)=>[d.variantId,d.transformationType,d.provider,`${d.baseGoldAction}→${d.variantGoldAction}`,`${d.baseModelAction??'ERROR'}→${d.variantModelAction??'ERROR'}`,String(d.observedActionChange),String(d.correctRequiredActionChange),String(d.exactGoldTransition)])),'','The case-level JSON contains all eight Base/Variant Gold labels, model outputs and native probabilities, expected and observed atomic changes, rules, latency, tokens, cost, and error details.'];await writeFile(join(directory,'case-level-transitions.md'),['# Sensitivity case-level transitions','',...cm].join('\n'));
 const am=[table(['Judgment','Provider','Expected changed','Exact Gold transitions','Missed','Wrong direction','Recovered from wrong Base','Unexpected on stable Gold'],atomicByJudgment.flatMap(p=>Object.entries(p.judgments).map(([id,a]:any)=>[id,p.provider,a.expectedChanged,a.correctlyChangedExactGoldTransition,a.missedExpectedChanges,a.wrongDirectionChanges,a.recoveredFromWrongBase,a.unexpectedChanges]))),'','A wrong Base label that changes to the correct Variant label is recorded separately from an exact Gold-to-Gold transition.'];await writeFile(join(directory,'atomic-sensitivity-report.md'),['# Atomic sensitivity report','',...am].join('\n'));
 const sm=[table(['Provider','Stability: action maintained','Responsiveness: changed to Variant Gold','Exact Base-Gold→Variant-Gold'],stabilityResponsiveness.map(x=>[x.provider,`${x.stabilityMeaningPreservingActionMaintained.count}/48`,`${x.responsivenessCorrectRequiredActionChange.count}/9`,`${x.exactBaseGoldToVariantGoldTransition.count}/9`])),'','Repeatability tests the same input, Consistency tests a meaning-preserving change, and Sensitivity tests a decision-relevant change. No combined score is produced.'];await writeFile(join(directory,'stability-responsiveness.md'),['# Stability and responsiveness','',...sm].join('\n'));
 manifest={...manifest,providers:configs.map(c=>({...manifest.providers.find((p:any)=>p.provider===c.provider),resolvedModel:(()=>{const x=[...new Set(records.filter(r=>r.provider===c.provider&&r.modelResolved).map(r=>r.modelResolved))];return x.length===1?x[0]:null;})()})),executionEndedAt:new Date().toISOString(),wallElapsedMs:summary.wallElapsedMs,complete:summary.complete};await writeFile(join(directory,'manifest.json'),JSON.stringify(manifest,null,2));
 return{directory,records,summary};
}
