import { createHash, randomUUID } from 'node:crypto';
import { appendFile, mkdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { buildState, decide, QUESTIONS } from './judgments.ts';
import { buildRequest, config, invoke } from './providers.ts';
import { fixtureFetch } from './runner.ts';
import { BENCHMARK_MANIFEST_HASH, EXECUTION_FREEZE, verifyExecutionFreeze } from './frozen-benchmark.ts';
import type { Action, Answer, Answers, Provider, RunRecord, Scenario } from './types.ts';

const benchmarkDir = 'benchmark/v1';
const defaultBaseRun = 'results/benchmark-v1/2026-09-23T02-04-26-591Z-frozen-benchmark-v1-live';
const shaJson = (x: unknown) => createHash('sha256').update(JSON.stringify(x)).digest('hex');
const readJson = async (path: string) => JSON.parse(await readFile(path, 'utf8'));
const actions: Action[] = ['CLEAR', 'QUESTION', 'INSPECT', 'DENY'];
const labels = (answer: Answer) => answer.type === 'noul' ? answer.noul! >= 0.5 : answer.type === 'choice' ? answer.choice : Number(Object.entries(answer.probabilities!).sort((a,b) => b[1]-a[1])[0][0]);
const percentile = (values: number[], p: number) => values.length ? [...values].sort((a,b) => a-b)[Math.ceil(values.length*p)-1] : null;
const stats = (values: number[]) => values.length ? {count:values.length,min:Math.min(...values),max:Math.max(...values),mean:values.reduce((a,b)=>a+b,0)/values.length,range:Math.max(...values)-Math.min(...values)} : {count:0,min:null,max:null,mean:null,range:null};
const matches = (answers: Answers, expected: Record<string,boolean|string|number>) => Object.fromEntries(Object.entries(expected).map(([id,gold])=>[id,labels(answers[id])===gold]));

function atomicStats(rows: RunRecord[], id: string) {
  const ok = rows.filter(r => r.answers?.[id]);
  const classified = ok.map(r => String(labels(r.answers![id])));
  const counts = Object.fromEntries([...new Set(classified)].sort().map(x=>[x,classified.filter(y=>y===x).length]));
  const modalCount = Math.max(0,...Object.values(counts));
  const sample = ok[0]?.answers![id];
  const probabilityVariation = sample?.type === 'noul'
    ? {pYes:stats(ok.map(r=>r.answers![id].noul!))}
    : Object.fromEntries(Object.keys(sample?.probabilities??{}).map(key=>[key,stats(ok.map(r=>r.answers![id].probabilities![key]))]));
  return {decisionCounts:counts,successful:ok.length,modalDecisionAgreement:ok.length?modalCount/ok.length:null,all5Agreement:ok.length===5&&modalCount===5,groundTruthMatches:rows.filter(r=>r.atomicMatches?.[id]).length,groundTruthAccuracy:rows.length?rows.filter(r=>r.atomicMatches?.[id]).length/rows.length:null,probabilityVariation,...(sample?.type==='score'?{expectedScoreVariation:stats(ok.map(r=>r.answers![id].score!))}:{}),...(rows[0]?.provider==='jev'&&sample?.type!=='noul'?{jevConfidenceVariation:stats(ok.map(r=>r.answers![id].confidence!).filter(Number.isFinite))}:{})};
}

function performanceMetrics(rows:RunRecord[]) {
  const times=rows.filter(r=>r.status==='ok').map(r=>r.latencyMs);
  const usage=(key:'inputTokens'|'cachedInputTokens'|'cacheWriteTokens'|'outputTokens'|'reasoningTokens')=>rows.reduce((n,r)=>n+(r.usage?.[key]??0),0);
  return {latencyMeanMs:times.length?times.reduce((a,b)=>a+b,0)/times.length:null,latencyP50Ms:percentile(times,.5),latencyP95Ms:percentile(times,.95),totalInferenceLatencyMs:rows.reduce((n,r)=>n+r.latencyMs,0),inputTokens:usage('inputTokens'),cachedInputTokens:usage('cachedInputTokens'),cacheWriteTokens:usage('cacheWriteTokens'),outputTokens:usage('outputTokens'),reasoningTokens:usage('reasoningTokens'),totalEstimatedCostUsd:rows.reduce((n,r)=>n+(r.estimatedCostUsd??0),0),costComplete:rows.every(r=>r.costComplete),apiErrors:rows.filter(r=>r.status==='error').length,retries:rows.reduce((n,r)=>n+Math.max(0,r.attempts.length-1),0)};
}

function reportMarkdown(cases:any[],summary:any) {
  const lines=['# Frozen Held-out Benchmark v1 — Repeatability','',`Execution freeze: \`${EXECUTION_FREEZE}\`. Repeatability requests are independent of the Base Benchmark responses.`,'','| Provider | All-5 cases | Mean modal agreement | Final accuracy | Errors | Retries |','|---|---:|---:|---:|---:|---:|'];
  for(const p of summary.providers)lines.push(`| ${p.provider} | ${p.exactRepeatabilityCases}/20 | ${(p.meanModalAgreement*100).toFixed(1)}% | ${p.finalCorrect}/100 | ${p.performance.apiErrors} | ${p.performance.retries} |`);
  lines.push('','Jev confidence and Luna generated probabilities remain separate provider-native values. Full atomic distributions, raw responses, and per-run data are in case-report.json and records.jsonl.','');
  for(const c of cases){lines.push(`## ${c.caseId} — Gold ${c.goldAction}`,'','| Provider | Base action | Five repeat actions | Modal | Modal agreement | All 5 | Gold matches |','|---|---|---|---|---:|---|---:|');for(const p of c.providers)lines.push(`| ${p.provider} | ${p.base.action??'ERROR'} | ${p.runs.map((r:any)=>r.action??'ERROR').join(', ')} | ${p.modalAction??'none'} | ${p.modalAgreementRate===null?'n/a':(p.modalAgreementRate*100).toFixed(0)+'%'} | ${p.all5Agreement?'yes':'no'} | ${p.groundTruthMatches}/5 |`);lines.push('','Atomic decisions, probability variation, decision rules, latency, token usage, cost, and errors are in case-report.json.','');}
  return lines.join('\n')+'\n';
}

export async function runFrozenRepeatability(options:{offline?:boolean;outputRoot?:string;baseRunDirectory?:string;onRecord?:(r:RunRecord)=>void}={}) {
  const gate=await verifyExecutionFreeze();
  if(!gate.pass)throw new Error(`Frozen benchmark integrity failed: ${JSON.stringify(gate.mismatches)}`);
  if(gate.freeze.components.repeatabilitySubset!==shaJson(gate.manifest.repeatability))throw new Error('Repeatability subset/configuration hash mismatch');
  if(gate.manifest.repeatability.repetitionsPerModelPlanned!==5||gate.manifest.repeatability.caseIds.length!==20||new Set(gate.manifest.repeatability.caseIds).size!==20)throw new Error('Frozen repeatability configuration is not 20 cases × 5 repeats');
  const [cases,gold,baseManifest,baseText]=await Promise.all([readJson(join(benchmarkDir,'cases.json')),readJson(join(benchmarkDir,'gold-proposed.json')),readJson(join(options.baseRunDirectory??defaultBaseRun,'manifest.json')),readFile(join(options.baseRunDirectory??defaultBaseRun,'records.jsonl'),'utf8')]);
  if(baseManifest.mode!=='live'||baseManifest.suite!=='frozen-base-only'||!baseManifest.complete||baseManifest.executionFreezeHash!==EXECUTION_FREEZE||baseManifest.benchmarkManifestHash!==BENCHMARK_MANIFEST_HASH)throw new Error('Base Benchmark provenance mismatch');
  const baseRecords:RunRecord[]=baseText.trim().split('\n').map(line=>JSON.parse(line));
  if(baseRecords.length!==240||new Set(baseRecords.map(r=>r.caseId)).size!==120)throw new Error('Base Benchmark record count mismatch');
  const selected:Scenario[]=gate.manifest.repeatability.caseIds.map((id:string)=>{const s=cases.find((c:Scenario)=>c.id===id);if(!s||s.variant!=='base'||!gold[id]?.scoringEligible)throw new Error(`Invalid frozen repeatability case ${id}`);return s;});
  for(const s of selected)for(const provider of ['jev','llm'] as Provider[]){const b=baseRecords.filter(r=>r.caseId===s.id&&r.provider===provider);if(b.length!==1||b[0].stateHash!==shaJson(buildState(s)))throw new Error(`Base result missing or state mismatch: ${s.id} ${provider}`);}
  const configs=(['jev','llm'] as Provider[]).map(config);
  for(const c of configs){const frozen=gate.manifest.modelSettings[c.provider];if(c.model!==frozen.model||c.reasoningEffort!==(frozen.reasoningEffort??null))throw new Error(`Model settings differ from freeze for ${c.provider}`);if(!options.offline&&!c.key)throw new Error(`Missing API key for ${c.provider}`);}
  const runId=`${new Date().toISOString().replace(/[:.]/g,'-')}-frozen-repeatability-v1-${options.offline?'offline-fixture':'live'}-${randomUUID().slice(0,8)}`;
  const directory=join(options.outputRoot??'results/benchmark-v1',runId);await mkdir(directory,{recursive:true});
  const startedAt=new Date().toISOString();const baseRecordsHash=createHash('sha256').update(baseText).digest('hex');
  let manifest:any={schemaVersion:1,runId,benchmarkVersion:'v1',suite:'frozen-repeatability-only',mode:options.offline?'offline-fixture':'live',excludedFromBaseAccuracy:true,executionFreezeHash:EXECUTION_FREEZE,benchmarkManifestHash:BENCHMARK_MANIFEST_HASH,repeatabilitySubsetHash:gate.freeze.components.repeatabilitySubset,casesHash:gate.freeze.components.cases,goldHash:gate.freeze.components.gold,judgmentsSourceHash:gate.freeze.components.judgmentsSource,humanReviewStatus:gate.freeze.humanReviewStatus,caseIds:selected.map(s=>s.id),repeatCount:5,baseRunDirectory:options.baseRunDirectory??defaultBaseRun,baseRecordsHash,modelSettings:gate.manifest.modelSettings,providers:configs.map(c=>({provider:c.provider,requestedModel:c.model,resolvedModel:null,reasoningEffort:c.reasoningEffort,pricingAssumptions:c.pricingAssumptions})),executionStartedAt:startedAt,executionEndedAt:null,execution:'20 frozen cases × 5 new requests per provider; sequential; provider order alternates for each case/repeat pair; application cache disabled; Base responses are comparison only',apiErrorRetryPolicy:'Retry HTTP 429/500/502/503/504/529 once; honor Retry-After up to 30 seconds; do not retry ambiguous network failures; persist all attempts and failures.',probabilitySemantics:'Jev Noul P(Yes), Choice/Score distributions and Jev confidence are provider-native. Luna probabilities are generated self-estimates, not the same confidence metric.',preRunIntegrity:{pass:true,componentMismatches:0},complete:false};
  await writeFile(join(directory,'manifest.json'),JSON.stringify(manifest,null,2));
  await writeFile(join(directory,'frozen-input-snapshot.json'),JSON.stringify({freeze:gate.freeze,benchmarkManifest:gate.manifest,cases:selected,gold:Object.fromEntries(selected.map(s=>[s.id,gold[s.id]])),baseRecordsHash},null,2));
  const records:RunRecord[]=[];let stop=false;let pair=0;const wallStart=performance.now();
  for(const s of selected){for(let repeatIndex=1;repeatIndex<=5&&!stop;repeatIndex++){const state=buildState(s);const ordered=pair++%2? [...configs].reverse():configs;for(const c of ordered){const request=buildRequest(c.provider,c.model,state,c.reasoningEffort);const started=new Date().toISOString();const response=await invoke(c,request,options.offline?fixtureFetch(c.provider):fetch);const decision=response.answers?decide(response.answers):null;const record:RunRecord={schemaVersion:1,runId,mode:options.offline?'offline-fixture':'live',repeatIndex,caseId:s.id,baseId:s.id,variant:'base',provider:c.provider,modelRequested:c.model,reasoningEffort:c.reasoningEffort,stateHash:shaJson(state),request,groundTruth:gold[s.id],decision,correct:decision?decision.action===gold[s.id].correctAction:null,atomicMatches:response.answers?matches(response.answers,gold[s.id].expected):null,status:response.answers?'ok':'error',startedAt:started,firstAttemptLatencyMs:response.attempts[0]?.latencyMs??0,...response};records.push(record);await appendFile(join(directory,'records.jsonl'),JSON.stringify(record)+'\n');options.onRecord?.(record);if(response.attempts.some(a=>[401,402,403].includes(a.status!)))stop=true;}}}
  const caseReports=selected.map(s=>({caseId:s.id,goldAction:gold[s.id].correctAction,providers:(['jev','llm'] as Provider[]).map(provider=>{const rows=records.filter(r=>r.caseId===s.id&&r.provider===provider);const base=baseRecords.find(r=>r.caseId===s.id&&r.provider===provider)!;const counts=Object.fromEntries(actions.map(a=>[a,rows.filter(r=>r.decision?.action===a).length]));const modalCount=Math.max(0,...Object.values(counts));const modalAction=modalCount?actions.find(a=>counts[a]===modalCount)!:null;return{provider,base:{action:base.decision?.action??null,correct:base.correct,rule:base.decision?.rule??null,atomicMatches:base.atomicMatches,answers:base.answers},runs:rows.map(r=>({repeatIndex:r.repeatIndex,action:r.decision?.action??null,rule:r.decision?.rule??null,correct:r.correct,atomicMatches:r.atomicMatches,answers:r.answers,latencyMs:r.latencyMs,firstAttemptLatencyMs:r.firstAttemptLatencyMs,usage:r.usage,estimatedCostUsd:r.estimatedCostUsd,status:r.status,error:r.error,retries:Math.max(0,r.attempts.length-1)})),actionCounts:counts,modalAction,modalAgreementRate:rows.length?modalCount/rows.length:null,all5Agreement:rows.length===5&&modalCount===5,groundTruthMatches:rows.filter(r=>r.correct).length,atomic:Object.fromEntries(Object.keys(QUESTIONS).map(id=>[id,atomicStats(rows,id)]))};})}));
  const providerSummaries=(['jev','llm'] as Provider[]).map(provider=>{const rows=records.filter(r=>r.provider===provider);const casesForProvider=caseReports.map(c=>c.providers.find((p:any)=>p.provider===provider));return{provider,attempted:rows.length,successful:rows.filter(r=>r.status==='ok').length,exactRepeatabilityCases:casesForProvider.filter((p:any)=>p.all5Agreement).length,meanModalAgreement:casesForProvider.reduce((n:number,p:any)=>n+(p.modalAgreementRate??0),0)/casesForProvider.length,finalCorrect:rows.filter(r=>r.correct).length,finalActionAccuracy:rows.filter(r=>r.correct).length/100,atomic:Object.fromEntries(Object.keys(QUESTIONS).map(id=>{const byCase=casesForProvider.map((p:any)=>p.atomic[id]);return[id,{all5AgreementCases:byCase.filter((x:any)=>x.all5Agreement).length,all5AgreementRate:byCase.filter((x:any)=>x.all5Agreement).length/20,meanModalDecisionAgreement:byCase.reduce((n:number,x:any)=>n+(x.modalDecisionAgreement??0),0)/20,groundTruthMatches:rows.filter(r=>r.atomicMatches?.[id]).length,groundTruthAccuracy:rows.filter(r=>r.atomicMatches?.[id]).length/100}]})),performance:performanceMetrics(rows)};});
  const summary={benchmarkVersion:'v1',suite:'frozen-repeatability-only',excludedFromBaseAccuracy:true,executionFreezeHash:EXECUTION_FREEZE,repeatabilitySubsetHash:gate.freeze.components.repeatabilitySubset,caseCount:20,repeatsPerProvider:5,expectedRequests:200,requestRecords:records.length,complete:records.length===200,providers:providerSummaries,wallElapsedMs:performance.now()-wallStart};
  await writeFile(join(directory,'summary.json'),JSON.stringify(summary,null,2));await writeFile(join(directory,'case-report.json'),JSON.stringify(caseReports,null,2));await writeFile(join(directory,'case-report.md'),reportMarkdown(caseReports,summary));await writeFile(join(directory,'post-run-observations.json'),JSON.stringify({benchmarkVersion:'v1',freezeHash:EXECUTION_FREEZE,datasetMutations:0,observations:[]},null,2));
  manifest={...manifest,providers:configs.map(c=>({...manifest.providers.find((p:any)=>p.provider===c.provider),resolvedModel:(()=>{const x=[...new Set(records.filter(r=>r.provider===c.provider&&r.modelResolved).map(r=>r.modelResolved))];return x.length===1?x[0]:null;})()})),executionEndedAt:new Date().toISOString(),wallElapsedMs:summary.wallElapsedMs,complete:summary.complete};await writeFile(join(directory,'manifest.json'),JSON.stringify(manifest,null,2));
  return{directory,summary,caseReports,records};
}
